name: Retrieval PyTorch Tests for Target Determination

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  llm-retrieval:
    runs-on: linux.4xlarge
    steps:
      - name: Clone PyTorch
        uses: actions/checkout@v3
        with:
          repository: pytorch/pytorch
          fetch-depth: 0
          path: pytorch

      - name: Setup Linux
        uses: ./pytorch/.github/actions/setup-linux

      - name: Clone CodeLlama
        uses: actions/checkout@v3
        with:
          repository: osalpekar/codellama
          ref: main
          path: codellama

      - name: Clone Target Determination Code
        uses: actions/checkout@v3
        with:
          repository: clee2000/llm-target-determinator
          ref: main
          path: llm-target-determinator

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniconda-version: "py39_4.12.0"
          python-version: 3.9

      - name: Install Requirements
        shell: bash -l {0}
        run: |
          set -euxo pipefail
          conda create \
            --yes \
            --quiet \
            --name "tdenv" \
            "python=3.9"
          conda activate tdenv
          pip install awscli==1.29.40
          cd "${GITHUB_WORKSPACE}/llm-target-determinator"
          pip install -r requirements.txt
          cd ../codellama
          pip install -e .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_target_determinator_s3_read
          aws-region: us-east-1

      - name: Fetch CodeLlama Checkpoint
        shell: bash -l {0}
        run: |
          set -euxo pipefail
          conda activate tdenv
          cd codellama/
          mkdir "CodeLlama-7b-Python"
          aws s3 cp "s3://target-determinator-assets/CodeLlama-7b-Python" "CodeLlama-7b-Python" --recursive --no-progress

      - name: Fetch indexes
        shell: bash -l {0}
        run: |
          set -euxo pipefail
          conda activate tdenv
          cd "${GITHUB_WORKSPACE}"/llm-target-determinator/assets
          aws s3 cp "s3://target-determinator-assets/indexes/indexer-functions.zip" "indexer-functions.zip" --no-progress
          unzip indexer-functions.zip
          rm indexer-functions.zip
          aws s3 cp "s3://target-determinator-assets/indexes/indexer-files.zip" "indexer-files.zip" --no-progress
          unzip indexer-files.zip
          rm indexer-files.zip

      - name: Run Retriever
        id: run_retriever
        shell: bash -l {0}
        run: |
          set -euxo pipefail
          conda activate tdenv
          cd "${GITHUB_WORKSPACE}"/llm-target-determinator
          torchrun \
            --standalone \
            --nnodes=1 \
            --nproc-per-node=1 \
            retriever.py \
            --experiment-name indexer-functions \
            --pr-parse-format GITDIFF
          cd assets
          zip -r "${GITHUB_WORKSPACE}"/mappings.zip mappings

      - name: Upload results to s3
        uses: seemethere/upload-artifact-s3@v5
        if: steps.run_retriever.outcome == 'success'
        with:
          name: llm_results
          retention-days: 14
          if-no-files-found: warn
          path: llm-target-determinator/assets/mappings.zip
